// This file is generated by npm run build:icons

export const iconNames = [
  "add",
  "blanket",
  "breakfast",
  "bubble-tea",
  "cancel",
  "cereal",
  "diaper",
  "document-money",
  "dollars",
  "email",
  "facebook-verified",
  "facebook",
  "folder",
  "image",
  "kindergarten",
  "menu",
  "milk-bottle",
  "newspaper",
  "next",
  "offer",
  "ok",
  "pacifier",
  "phone-call",
  "piggy-bank",
  "prev",
  "salad",
  "shoes",
  "web",
] as const;

export type IconName = (typeof iconNames)[number];
