import type { Metadata } from "next";
import "#app/styles/global.css";
import { roboto, robotoCondensed } from "#app/styles/font.ts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${robotoCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
