import type { Metadata } from "next";
import "#app/styles/global.css";
import { roboto, robotoCondensed } from "#app/styles/font.ts";
import { AppContainer, Main } from "#app/components/templates";
import { Header, Footer } from "#app/components/organisms";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${robotoCondensed.variable} antialiased bg-background text-foreground`}
      >
        <AppContainer>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </AppContainer>
      </body>
    </html>
  );
}
